name: task-manager-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.13"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.dev.txt
          python -m pip install -r requirements.src.txt
  
      - name: Run tests
        run: |
          pytest -v --maxfail=1 --disable-warnings --color=yes

      - name: Verify project builds
        run: |
          python -m pip install build
          python -m build --wheel --sdist
          ls -l dist/
          test -f dist/*.whl
          test -f dist/*.tar.gz
