name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.dev.txt
          python -m pip install -r requirements.src.txt
      - name: Run tests
        run: |
          pytest -v --maxfail=1 --disable-warnings --color=yes
      - name: Verify project builds
        run: |
          python -m pip install build
          python -m build --wheel --sdist
          ls -l dist/
          test -f dist/*.whl
          test -f dist/*.tar.gz
